# Generated by Django 3.0.1 on 2020-02-26 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSwitch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('address', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('port_number', models.CharField(default='-', max_length=4)),
                ('state', models.CharField(default='-', max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powerswitch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PowerSwitchSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset', models.IntegerField(blank=True, choices=[(1, 'Reset')], null=True)),
                ('default_state', models.CharField(choices=[('off', 'Off'), ('on', 'On')], default='off', max_length=8)),
                ('auto_off', models.IntegerField(blank=True, default=0, null=True)),
                ('state', models.CharField(default='-', max_length=1000)),
                ('schedule', models.BooleanField(default=False)),
                ('schedule_rules', models.CharField(blank=True, default='', help_text='Format: 0900-on,0930-off', max_length=1000, null=True)),
                ('powerswitch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='powerswitch_settings', to='powerswitches.PowerSwitch')),
            ],
        ),
        migrations.CreateModel(
            name='PowerSwitchRelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_state', models.CharField(choices=[('off', 'Off'), ('on', 'On'), ('toggle', 'Toggle')], default='off', max_length=8)),
                ('timer', models.IntegerField(blank=True, default=0, null=True)),
                ('state', models.CharField(default='-', max_length=1000)),
                ('powerswitch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='powerswitch_relay', to='powerswitches.PowerSwitch')),
            ],
        ),
    ]
