# Generated by Django 3.0.1 on 2020-01-26 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedLightData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_data', models.FileField(blank=True, upload_to='assets/ledlights/')),
                ('active', models.BooleanField(default=False)),
                ('led_light', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledlightdata', to='lights.LedLight')),
            ],
        ),
    ]
