# Generated by Django 2.2.7 on 2019-11-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledlight',
            name='port_number',
            field=models.CharField(default='-', max_length=4),
        ),
    ]
