# Generated by Django 2.1.7 on 2019-03-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledlight',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
